FROM ubuntu:20.04

LABEL Maintainer="moalmo"

WORKDIR /usr/app/such 

COPY stun.py ./ 

RUN apt-get update && \
 apt-get install -y python3 

RUN apt-get -y install python3-pip
RUN pip install --no-cache-dir


CMD ["python3", "./stun.py"]